package apeman_core.base_entities

import java.util.*

enum class FeatureType {
    NUM_LITERAL,
    NUM_CONDITIONAL,
    NUM_SWITCH,
    NUM_TYPE_ACCESS,
    NUM_INVOCATION,
    NUM_IF,
    NUM_ASSIGN,
    NUM_TYPED_ELEMENTS,
    NUM_VAR_ACCESS,
    NUM_FIELD_ACCESS,
    NUM_LOCAL,
    NUM_PACKAGE,

    // there aren't CON_LOC!
    // also CON_ASSERT
    LOC_CANDIDATE,
    LOC_RATIO,

    CON_LITERAL,
    CON_CONDITIONAL,
    CON_SWITCH,
    CON_TYPE_ACCESS,
    CON_INVOCATION,
    CON_IF,
    CON_ASSIGN,
    CON_TYPED_ELEMENTS,
    CON_VAR_ACCESS,
    CON_FIELD_ACCESS,
    CON_LOCAL,
    CON_PACKAGE,

    VAR_ACCESS_COUPLING,
    VAR_ACCESS_COUPLING_2,
    VAR_ACCESS_COHESION,
    VAR_ACCESS_COHESION_2,

    FIELD_ACCESS_COUPLING,
    FIELD_ACCESS_COUPLING_2,
    FIELD_ACCESS_COHESION,
    FIELD_ACCESS_COHESION_2,

    INVOCATION_COUPLING,
    INVOCATION_COHESION,

    TYPED_ELEMENTS_COUPLING,
    TYPED_ELEMENTS_COHESION,

    TYPE_ACCESS_COUPLING,
    TYPE_ACCESS_COUPLING_2,
    TYPE_ACCESS_COHESION,
    TYPE_ACCESS_COHESION_2,

    PACKAGE_COUPLING,
    PACKAGE_COUPLING_2,
    PACKAGE_COHESION,
    PACKAGE_COHESION_2
}

typealias Features = EnumMap<FeatureType, Double>
